swagger: "2.0"
info:
  version: "1.0.0"
  title: "User API"
  description: "API for creating, retrieving, updating, and deleting user information"
  contact:
    name: "Your Name"
paths:
  /users.php:
    get:
      summary: "Get Users"
      description: "Get a list of users"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                  format: "int64"
                name:
                  type: "string"
                email:
                  type: "string"
        500:
          description: "Internal server error"
      tags:
        - "Users"
        
    post:
      summary: "Create User"
      description: "Create a new user"
      consumes:
        - application/json
      parameters:
        - in: "body"
          name: user
          description: The user to create.
          schema:
            type: object
            required:
              - user
            properties:
              user:
                type: string
              email:
                type: string
      responses:
        201:
          description: "User created successfully"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
              email:
                type: "string"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
      tags:
        - "Users"

    put:
      summary: "Update User"
      description: "Update an existing user"
      parameters:
        - name: "id"
          in: "body"
          description: "User ID"
          required: true
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
              email:
                type: "string"
      responses:
        200:
          description: "User updated successfully"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
              email:
                type: "string"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
      tags:
        - "Users"

    delete:
      summary: "Delete User"
      description: "Delete a user by ID"
      parameters:
        - name: "id"
          in: "body"
          description: "User ID"
          required: true
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
      responses:
        200:
          description: "User deleted successfully"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
      tags:
        - "Users"

  /user.php:
    get:
      summary: "Get User by ID"
      description: "Get a user by ID"
      parameters:
        - name: "id"
          in: "query"
          description: "User ID"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
              email:
                type: "string"
        400:
          description: "Bad request"
        500:
          description: "Internal server error"
